### PR TITLE
Hrinfo 947 tabs

### PR DESCRIPTION
**Pull request by attiks**

### CODE REVIEW

**Review by rupl — CHANGES_REQUESTED** [review]
@attiks for the tabs whose paths changed in the diff, I see the expected path aliases like so: `/country/maps`, `/country/reports`

However for the ones whose diffs did not change in this branch, even after I re-saved the Operation with the new alias, and then saved each node with an automatic alias, I'm still seeing the format `/operations/country/assessments` — for the following tabs:

- Assessments
- Data
- Events
- Contacts

Here's one screenshot since they're all identical:

Screen Shot 2022-04-26 at 16 26 35

**Comment by attiks** [comment]
Best to delete all aliases at `/admin/config/search/path/delete_bulk`

They are not being generated again using `/operations/`

**Review by rupl — APPROVED** [review]
I tried again no change. But anyway the content will be wiped for prod so I'm guessing it won't matter?

**Comment by attiks** [comment]
> I tried again no change. But anyway the content will be wiped for prod so I'm guessing it won't matter?

Which aliases are being created at `admin/config/search/path`

**Comment by rupl** [comment]
I made sure to delete all of them this time (the first bulk delete I didn't do correctly and didn't check) and once all aliases had truly been cleared, I resaved some entitites and see the correct paths. 

Sorry for my fumbling as I test! Merge away  :shipit:

**Pull request merged**
