### PR TITLE
Hrinfo 1211

### PR DESCRIPTION
**Pull request by attiks**

### CODE REVIEW

**Review by rupl — CHANGES_REQUESTED** [review]
Does this need `drupal/override_node_options` added to composer? When I first tried importing config, it complains about two things:

- Paragraph type "Recent assessments" has content (solved by deleting manually)
- Unable to install the `override_node_options` module since it does not exist

**Comment by attiks** [comment]
First https://github.com/UN-OCHA/operations-site/pull/81

**Review by rupl — APPROVED** [review]
you left me nothing to do!!!!

Screen Shot 2022-04-13 at 12 03 28

**Comment by rupl** [comment]
Heads up that despite merging the other PR, this one doesn't seem to have updated itself to point at `develop` branch like it normally does.

**Pull request merged**
